# Generated by Django 3.2.10 on 2021-12-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=400)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thumbnail_url', models.CharField(max_length=500)),
                ('vid_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['-published_at'], name='video_searc_publish_e40322_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['vid_id'], name='video_searc_vid_id_0545c2_idx'),
        ),
    ]
